# Generated by Django 5.1.4 on 2025-01-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, upload_to='products/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.ImageField(default=None, upload_to='stores/%Y/%m/%d'),
        ),
    ]
