# Generated by Django 5.1.4 on 2025-01-19 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradings', '0002_alter_product_image_alter_store_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
