# Generated by Django 5.1.4 on 2025-01-19 15:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradings', '0003_rename_created_date_store_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
