# Generated by Django 5.1.4 on 2025-01-22 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradings', '0005_alter_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='business_name',
            new_name='store_name',
        ),
    ]
