# Generated by Django 5.1.4 on 2025-01-22 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradings', '0006_rename_business_name_seller_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='seller',
            field=models.ForeignKey(limit_choices_to={'role': 'seller'}, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
