<<<<<<< HEAD
# Generated by Django 5.1.4 on 2025-01-22 14:19
=======
# Generated by Django 5.1.4 on 2025-01-23 12:11
>>>>>>> 612c96cea1dcb867475e7729612035ed79ecaafd

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradings', '0007_alter_store_seller_delete_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(default=None, upload_to='category/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tradings.category'),
        ),
    ]
