# Generated by Django 5.1.4 on 2025-01-23 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradings', '0008_category_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
