# Generated by Django 5.1.4 on 2025-01-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradings', '0012_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
