# Generated by Django 5.1.4 on 2025-01-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradings', '0013_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
