# Generated by Django 5.1.4 on 2025-01-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradings', '0014_alter_store_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
            preserve_default=False,
        ),
    ]
