# Generated by Django 5.1.4 on 2025-01-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradings', '0015_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=10),
        ),
    ]
