# Generated by Django 5.1.4 on 2025-01-30 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradings', '0019_order_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='store',
        ),
    ]
