# Generated by Django 5.1.4 on 2025-01-31 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradings', '0019_alter_review_options_review_parent_review'),
        ('tradings', '0020_remove_order_store'),
    ]

    operations = [
    ]
