# Generated by Django 5.1.4 on 2025-01-31 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradings', '0021_merge_20250131_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='store',
        ),
    ]
