# Generated by Django 5.1.4 on 2025-01-31 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradings', '0022_remove_orderitem_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('employee', 'Employee'), ('seller', 'Seller'), ('buyer', 'Buyer')], default='admin', max_length=10),
        ),
    ]
