# Generated by Django 5.1.4 on 2025-02-05 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradings', '0021_merge_20250131_0828'),
        ('tradings', '0023_alter_user_role'),
    ]

    operations = [
    ]
